openapi: 3.0.3
info:
  title: RustOpus XML API
  version: 1.0.0
  description: Get Octopus 8 ERP SOAP XML with english tags instead of hungarians

paths:
  /get-products:
    get:
      summary: Get product data
      tags:
        - Products
      parameters:
        - name: url
          in: query
          required: true
          description: Endpoint URL with the ```.asmx``` file
          schema:
            type: string
        - name: authcode
          in: query
          required: true
          description: Authorization code
          schema:
            type: string
        - name: xmlns
          in: query
          required: false
          description: Optional XML namespace
          schema:
            type: string
      responses:
        '200':
          description: XML product list
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ProductResponse'

  /get-stocks:
    get:
      summary: Get stock data
      tags:
        - Stocks
      parameters:
        - name: url
          in: query
          required: true
          description: Endpoint URL with the ```.asmx``` file
          schema:
            type: string
        - name: authcode
          in: query
          required: true
          description: Authorization code
          schema:
            type: string
        - name: xmlns
          in: query
          required: false
          description: Optional XML namespace
          schema:
            type: string
      responses:
        '200':
          description: XML stock list
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/StockResponse'

  /get-prices:
    get:
      summary: Get price data
      tags:
        - Prices
      parameters:
        - name: url
          in: query
          required: true
          description: Endpoint URL with the ```.asmx``` file
          schema:
            type: string
        - name: authcode
          in: query
          required: true
          description: Authorization code
          schema:
            type: string
        - name: xmlns
          in: query
          required: false
          description: Optional XML namespace
          schema:
            type: string
        - name: pid
          in: query
          required: true
          description: Partner ID
          schema:
            type: integer
      responses:
        '200':
          description: XML price list
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/PriceResponse'
  
  /get-images:
    get:
      summary: Get image data
      tags:
        - Images
      parameters:
        - name: url
          in: query
          required: true
          description: Endpoint URL with the ```.asmx``` file
          schema:
            type: string
        - name: authcode
          in: query
          required: true
          description: Authorization code
          schema:
            type: string
        - name: xmlns
          in: query
          required: false
          description: Optional XML namespace
          schema:
            type: string
      responses:
        '200':
          description: XML image list
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/ImageResponse'
          
          
  
  /get-bulk:
    get:
      summary: Get bulk data (XML)
      tags:
        - Bulk
      parameters:
        - name: url
          in: query
          required: true
          description: Endpoint URL with the ```.asmx``` file
          schema:
            type: string
        - name: authcode
          in: query
          required: true
          description: Authorization code
          schema:
            type: string
        - name: xmlns
          in: query
          required: false
          description: Optional XML namespace
          schema:
            type: string
        - name: pid
          in: query
          required: true
          description: Partner ID
          schema:
            type: integer
      responses:
        '200':
          description: XML bulk list
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/BulkResponse'
    
components:
  schemas:
    ProductResponse:
      type: object
      xml:
        name: Envelope
      properties:
        body:
          type: object
          properties:
            response:
              type: object
              properties:
                result:
                  type: object
                  properties:
                    answer:
                      properties:
                        version:
                          type: string
                        error:
                          type: object
                          properties:
                            code:
                              type: number
                            description:
                              type: string
                        products:
                          type: array
                          items:
                            $ref: '#/components/schemas/ProductProducts'
  
    ProductProducts:
      type: object
      properties:
        product:
          type: object
          properties:
            id:
              type: number
            no:
              type: string
            name:
              type: string
            unit:
              type: string
            base_unit:
              type: string
            base_unit_qty:
              type: number
            brand:
              type: string
            category_code:
              type: string
            category_name:
              type: string
            description:
              type: string
            weight:
              type: number
            size:
              type: object
              properties:
                x:
                  type: number
                y:
                  type: number
                z:
                  type: number
            oem_code:
              type: string
            main_category_code:
              type: string
            main_category_name:
              type: string
            sell_unit:
              type: number
            origin_country:
              type: string
    
    StockResponse:
      type: object
      xml:
        name: Envelope
      properties:
        body:
          type: object
          properties:
            response:
              type: object
              properties:
                result:
                  type: object
                  properties:
                    answer:
                      type: object
                      properties:
                        version:
                          type: string
                        error:
                          type: object
                          properties:
                            code:
                              type: number
                            description:
                              type: string
                        products:
                          type: array
                          items:
                            $ref: '#/components/schemas/StockProducts'
          
    StockProducts:
      type: object
      xml:
        name: products
      properties:
        product:
          type: object
          properties:
            id:
              type: number
            no:
              type: string
            stock:
              type: number
    
    PriceResponse:
      type: object
      xml:
        name: Envelope
      properties:
        body:
          type: object
          properties:
            response:
              type: object
              properties:
                result:
                  type: object
                  properties:
                    answer:
                      type: object
                      properties:
                        version:
                          type: string
                        error:
                          type: object
                          properties:
                            code:
                              type: number
                            description:
                              type: string
                        products:
                          type: array
                          items:
                            $ref: '#/components/schemas/PriceProducts'

    PriceProducts:
      type: object
      xml:
        name: products
      properties:
        product:
          type: object
          properties:
            id:
              type: number
            no:
              type: string
            list_price:
              type: number
            price:
              type: number
            sale_price:
              type: number
            currency:
              type: string
              
    ImageResponse:
      type: object
      xml:
        name: Envelope
      properties:
        body:
          type: object
          properties:
            response:
              type: object
              properties:
                result:
                  type: object
                  properties:
                    answer:
                      type: object
                      properties:
                        version:
                          type: string
                        error:
                          type: object
                          properties:
                            code:
                              type: number
                            description:
                              type: string
                        products:
                          type: array
                          items:
                            $ref: '#/components/schemas/ImageProducts'
              
    ImageProducts:
      type: object
              
    BulkResponse:
      type: object
      xml:
        name: Envelope
      properties:
        body:
          type: object
          properties:
            response:
              type: object
              properties:
                result:
                  type: object
                  properties:
                    answer:
                      type: object
                      properties:
                        version:
                          type: string
                        error:
                          type: object
                          properties:
                            code:
                              type: number
                            description:
                              type: string
                        products:
                          type: array
                          items:
                            $ref: '#/components/schemas/BulkProducts'
      
    BulkProducts:
      type: object
      xml:
        name: products
      properties:
        product:
          type: object
          properties:
            id:
              type: number
            no:
              type: string
            name:
              type: string
            unit:
              type: string
            base_unit:
              type: string
            base_unit_qty:
              type: string
            brand:
              type: string
            oem_code:
              type: string
            category_code:
              type: string
            category_name:
              type: string
            description:
              type: string
            weight:
              type: number
            size:
              type: object
              properties:
                x:
                  type: number
                y:
                  type: number
                z:
                  type: number
            main_category_code:
              type: string
            main_category_name:
              type: string
            sell_unit:
              type: number
            origin_country:
              type: string
            price:
              type: number
            currency:
              type: string
            stock:
              type: number
            images:
              type: array
              items:
                $ref: '#/components/schemas/BulkImages'
                
    BulkImages:
      type: object
      xml:
        name: images
      properties:
        url:
          type: string
